input:
    size: (32, 32)
model:
    name: 'Resnet50'
    classes: 10
dataset:
    name: 'CIFAR10'
    dir: './datasets/cifar10'
    batch_size: 128
optim:
    name: 'sgd'
    base_lr: 0.1
    scheduler:
        name: 'MultiStepLR'
        milestones: [150, 250]
        gamma: 0.1
transforms:
    tensor:
        normalization: 
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
    img:
        aug_cifar: False
        resize:
            enable: 0
        random_crop:
            enable: 1
            padding: 4
        random_horizontal_flip:
            enable: 1
            p: 0.5
        random_vertical_flip:
            enable: 0
            p: 0.5
        random_rotation:
            enable: 0
trainer:
    default_root_dir: './output_cifar10'
    logger:
        setting: 0
        type: 'test_tube'
        mlflow:
            tracking_uri: './output_cifar10' 
        test_tube:
            save_dir: './output_cifar10'
            name: 'torchline_logs'
            version: -1 # if <0, then use default version
hooks:
    early_stopping:
        setting: 2
        patience: 20
        monitor: 'valid_acc_1'
        mode: 'max'
    model_checkpoint:
        setting: 2
        monitor: 'valid_acc_1'
        mode: 'max'
        filepath: ''
topk: [1, 3]
predict_only:
    type: 'ckpt'
    to_pred_file_path: '' # specify the path of images
    load_ckpt:
        checkpoint_path: '' # load_from_checkpoint
    load_metric:
        weights_path: '' # load_from_metrics
        tags_csv: ''
        on_gpu: True
        map_location: 'cuda:0'
